apiVersion: v1
kind: Namespace
metadata:
  name: crdnginx
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxs.mycrd.com
spec:
  group: mycrd.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string
                config-type:
                  type: string
                  nullable: true
  scope: Namespaced
  names:
    plural: nginxs
    singular: nginx
    kind: CrdNginx
    shortNames:
    - ngx

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: crdnginx
  name: crdnginx
  namespace: crdnginx
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crdnginx
  template:
    metadata:
      labels:
        app: crdnginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 10.15.10.37
                - 10.15.10.38
      containers:
      - env:
        - name: kube_config_host
          value: '10.103.10.5'
        - name: kube_config_port
          value: '6443'
        - name: kube_config_token
          value: YvoRAStw
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: hadals/crdnginx:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 12345
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: crdnginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete